# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='amount',
        ),
        migrations.AddField(
            model_name='item',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
